version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: